### ISSUE TITLE
AMD support

### ISSUE THREAD

**Issue by julianjc84** [matzman666/OpenVR-AdvancedSettings#1]
Advanced Settings works on my Nvidia 960
However my AMD 390x it does not draw the window.

**Comment by matzman666** [comment]
But you can see the round thumbnail in the dashboard?

I had the same problem on my Nvidia GPU and I solved it by adding a glFlush() after submitting the overlay texture. A lot of people on the internet say that some drivers implement glFlush() as no-op, does someone know if this is the case with AMD. I don't own an AMD GPU so I cannot check myself.

**Comment by julianjc84** [comment]
I have both AMD and nvidia in same machine same time just I just stop steamVR swap cables. 

Yes is can see the thumbnail in dashboard 
Yes I can click it 
With Nvidia works perfectly. 
With AMD card when I click the dashboard icon for advanced settings I can track feel the edge of where the window should be displaying. The vive blue cursor controller hits it. But it's invisible.

**Comment by matzman666** [comment]
Uploaded a [possible fix](https://github.com/matzman666/OpenVR-AdvancedSettings/releases/download/v1.1/OpenVR-AdvancedSettings-v1.1-amdfix.7z). Could you please try and tell me whether it is working.

**Comment by julianjc84** [comment]
No work, Same deal. Had a lot of issues getting the old build to stop loading. Ended up delete it. https://youtu.be/ndKfl2rj44k

**Comment by matzman666** [comment]
Fixed in version v1.1.1.

Problem was that Qt's OpenGL Painter is incompatible with OpenGL version >= 3.0, and my OpenGL context was 4.0. NVIDIA's OpenGL implementation does not care, but AMD's does.
