### ISSUE TITLE
restartvrserver.bat doesn't work for me

### ISSUE THREAD

**Issue by WildSide-VR** [matzman666/OpenVR-AdvancedSettings#11]
The restart feature doesn't work for me because it's a batch file with a hardcoded path to steamvr that is not correct on my system:

`start "" "C:\Program Files (x86)\Steam\steamapps\common\SteamVR\tools\bin\win32\vrmonitor.exe"`

The drive is wrong and also my directory is called "OpenVR" where you call out "SteamVR". Not sure why.

I can change this batch file to make it work but you need something like this:

`QSettings settings("HKEY_CURRENT_USER\\Software\\Valve\\Steam",
                   QSettings::NativeFormat);
QString sourcemods_path = settings.value( "SteamPath", "" ).toString();
if (!sourcemods_path.isEmpty())
{
    sourcemods_path += "\steamapps\common\OpenVR\tools\bin\win32\";
}`

**Comment by deinlandel** [comment]
Yep, same for me. Restarting from interface doesn't work. I alse have Steam installed to a custom dir.

**Comment by matzman666** [comment]
Will be fixed in the next version (implemented with commit 2bf12a4264b0c6fb41fcfbe4049133633ee18883).

**Comment by matzman666** [comment]
Uploaded a new version which fixes this problem, therefore I close this issue.
