### ISSUE TITLE
AMD strikes again

### ISSUE THREAD

**Issue by julianjc84** [matzman666/OpenVR-AdvancedSettings#12]
New update to AMD 16.11.4 drivers and breaks Advanced settings again. :( 

AMD
[INFO ] 2016-11-25 17:32:36: Starting Application.
[INFO ] 2016-11-25 17:32:36: Settings File: C:/Users/01/AppData/Roaming/matzman666/OpenVRAdvancedSettings.ini
[INFO ] 2016-11-25 17:32:36: VR Runtime Path: C:/Program Files (x86)/Steam/steamapps/common/SteamVR/
[FATAL] 2016-11-25 17:32:45: CRASH HANDLED; Application has crashed due to [SIGILL] signal

changed to NVIDIA and no issues.

**Comment by matzman666** [comment]
Does it still crash with the 16.11.5 hotfix? I don't have an AMD GPU and therefore cannot test it myself.

**Comment by julianjc84** [comment]
Solved 16.11.5 hotfix
