### ISSUE TITLE
error "another instance is already running"

### ISSUE THREAD

**Issue by kvdv99** [matzman666/OpenVR-AdvancedSettings#14]
It has always worked perfectly without any error.
But since today, after a reboot of my pc, I receive the error in the title.

Anything I can do? When I click OK, it just comes back after about 7 seconds.
Autostart is selected (a black square means selected, right? I always forget)

thanks for the support!

**Comment by ph2001** [comment]
Yep, program is becoming unusable for me... since the 2nd last beta, I get an AdvancedSettings.exe has stopped working error every time I leave SteamVR, since the newest one, this "another instance is already running" also pops up non stop. How to uninstall (for the time being)?

**Comment by CrazyCoder** [comment]
Same problem here.

**Comment by esabouraud** [comment]
Same issue here. It started with the latest SteamVR beta version. For now a simple workaround is to use SteamVR official (as in "non-beta") build.

**Comment by esabouraud** [comment]
Latest SteamVR beta build (1480731687) fixes this issue,

**Comment by matzman666** [comment]
Closed since it has been fixed with the latest beta.
