### ISSUE TITLE
UI scale problem for those of us with 4k monitors

### ISSUE THREAD

**Issue by darrellspivey** [matzman666/OpenVR-AdvancedSettings#15]
The entire interface inside the Vive seems to be scaled larger when the user's monitor resolution is set to 4k. The AdvancedSettings interface simply does not fit into the VR Dashboard screen. Text and sliders are cut off, and some buttons seem to be inaccessible. I haven't figured out how to save chaperone profiles, and I'm pretty sure it's just that I can't see a save button on the bottom of the interface...

Multiple reddit users had this problem as discussed in this thread:
https://www.reddit.com/r/Vive/comments/5gad3o/here_is_omething_called_advanced_settings_that/daqsbaj/ 

I'll try to add screenshots if you'd like after finals end on Tuesday.

**Comment by matzman666** [comment]
A fix will be provided with the next version. If you don't want to wait for the next version, [here](https://github.com/matzman666/OpenVR-AdvancedSettings/issues/4) are some instructions on how to fix this issue.

**Comment by darrellspivey** [comment]
Ah didn't see that. Thanks so much!

**Comment by matzman666** [comment]
Uploaded a new version which fixes this problem, therefore I close this issue.
