### ISSUE TITLE
steamvr settings missing or corrupt

### ISSUE THREAD

**Issue by rxstud2011** [matzman666/OpenVR-AdvancedSettings#17]
I get this error and no advence settings. it looks like ss is at 0.5

**Comment by matzman666** [comment]
What error? Is there a message box with an error message similar to the issue title? When you say that ss looks like 0.5, could it be that you are affected by [this issue](https://github.com/matzman666/OpenVR-AdvancedSettings/issues/8)?

**Comment by rxstud2011** [comment]
Yes! That's exactly the issue I'm having on Windows 10 x64 US.

**Comment by matzman666** [comment]
Fixed since version v.2.1, so I close the issue.
