### ISSUE TITLE
No more advanced settings menu in SteamVR in UI

### ISSUE THREAD

**Issue by rainabba** [matzman666/OpenVR-AdvancedSettings#20]
I tried 2.0 and for a couple sessions, I had the advanced settings option to the right of Steam, Desktop and Vive. It stopped showing. I saw that 2.1 was released so I shut down SteamVR and Steam, deleted the old folder, downloaded the new .7z, unpacked and ran AdvancedSettings.exe (when it was working, this made the new menu item appear).

I also tried the restartvrserver.bat and as far as I can tell, it has no effect. I'm hoping this behavior sheds some light on what's going on.

Am I missing something? Does it matter where the app is run from (another drive, particular folder, etc..)?

**Comment by matzman666** [comment]
What does your log file say? I should not matter at all from where the application is run.

**Comment by rainabba** [comment]
Have a chance to look into this again today. Expected the .log file to be in the top folder, but don't see one. Where do I find it?

**Comment by rainabba** [comment]
I tried again tonight and it wasn't working. I couldn't find the log and posted the previous, then tried running as Administrator and got it working. If that was in the instructions, I completely missed it, but it looks like I'm good now so I'm closing this.

**Comment by powersst** [comment]
Hey Rainabba, I am having the same problem and running the application as administrator causes the UI icon to not even show up. Any advice?
