### ISSUE TITLE
OpenVR Advanced Settings v2.1 grafic bug, need help

### ISSUE THREAD

**Issue by doenerkalle** [matzman666/OpenVR-AdvancedSettings#24]
![unbenannt](https://cloud.githubusercontent.com/assets/24865379/21582471/063c1d8e-d059-11e6-9273-d577d395b35a.jpg)

Hi, how can I fix this? After working for maybe 3 or 4 gaming sessions the overlay stopped working as usual. I can press all the buttons and sliders, but obvioiusly I don't see any text... It is a screenshot of the Desktop window, but the VR overlay looks the same. I've tried reinstalling several times without success. It's the newest version.
I've deleted the folder and deleted an .ini in the appdata folder of my w10 user account. I've also been paying attention to my task manager so there is no "old" AdvancedSettings.exe running when I start SteamVR.
Specs: i7 6700k, R9 290x 

thanks for your work!

**Comment by matzman666** [comment]
That's the first time I see something like this. You said it was working before, were there any significant events before ((GPU) driver update or something like this)? 
I have heard of problems with AMD GPUs not rendering stuff before, but I don't have an AMD GPU myself so it's hard for me to diagnose and fix problems only appearing on AMD GPUs.

**Comment by doenerkalle** [comment]
thanks, with the latest AMD drivers it works again.
