### ISSUE TITLE
2.2 install crash.

### ISSUE THREAD

**Issue by nygellyndley** [matzman666/OpenVR-AdvancedSettings#25]
Installing then running `AdvancedSettings.exe` results in nothing.  The advanced settings option does not appear in Steam.

Logs are showing an application crash.  I get this with both the installed and standalone versions when running `AdvancedSettings.exe`.

[AdvancedSettings.log.txt](https://github.com/matzman666/OpenVR-AdvancedSettings/files/691587/AdvancedSettings.log.txt)

I am installing with SteamVR running as per the instructions.
I have tried with both the current SteamVR and the beta version.

OpenVRAdvancedSettings 2.1 standalone installs and runs correctly.

**Comment by matzman666** [comment]
There was a bug that caused a crash when Revive was not installed. I uploaded a fixed version.

**Comment by nygellyndley** [comment]
sorted, thanks very much
