### ISSUE TITLE
Allow changing the audio input (micrphone) device

### ISSUE THREAD

**Issue by BrianGragg** [matzman666/OpenVR-AdvancedSettings#26]
Sometimes I need to switch between my headphones mic and my vive mic once in VR and it would be so much easier if I could do this within OpenVR Advanced Settings.

The primary reason for this is that I use Voice Attack with some games (like Elite Dangerous), but the vive mic does not work reliably with Voice Attack, so I wear my headphones and use that mic in those, usually seated, situations.  However, when playing multiplayer standing games I want to use the mic in the vive as it works acceptably for people to understand me.

**Comment by lghtanddrk** [comment]
I ran into the same issue too. Do you know if Open VR Advance Settings can be disabled by simply turning off the dashboard?  I use it just for the Revive.  I don't need it on for regular Steam VR games.

**Comment by lghtanddrk** [comment]
I'm also having people tell me that it sounds like my voice is going through a voice changer. I don't know if this is a bug from OpenVR Advanced Settings or the Revive.

**Comment by BrianGragg** [comment]
As far as I know it's just the crappy built-in vive micrphone that sounds bad.  I don't think Advanced Settings has anything to do with it, I just would like to use Advanced Settings to change the mic.

**Comment by matzman666** [comment]
Advanced Settings and Revive should not influence audio quality at all. When they do then it's a windows bug.

Will see what I can do about letting users change the audio device on the overlay.

**Comment by lghtanddrk** [comment]
I played Onward and Rec Room last night and the audio was fine.  I'm assuming it has to be a Revive bug because 2 games I played so far including Dead & Buried I was told that I sounded like I had a voice changer.  

I tried your method of going into Windows Sound Options to turn on the default but don't see the Vive HDMI microphone listed like in SteamVR settings.  There was a USB microphone listed so I assume it was that one.  The only other devices I have are Soundblaster Input which has nothing connected to it and my Microsoft Lifecam. It would be great to select it from OpenVR Advanced Settings.

**Comment by matzman666** [comment]
> including Dead & Buried I was told that I sounded like I had a voice changer.

Apparently there is a [bug in Dead & Buried](https://github.com/matzman666/OpenVR-AdvancedSettings/issues/27#issuecomment-271557325) that affects audio quality only for Vive users. Maybe other games are also affected, that's the only explanation I have.

**Comment by matzman666** [comment]
Added in version 2.3.

**Comment by lghtanddrk** [comment]
Great addition.  Thanks.  Only one issue.  It is not remembering the setting each time I launch SteamVR.  The settings show correctly in SteamVR settings but it is not matching in OpenVR Advanced Settings or remembering the setting I change it too.

There was an issue a while back where Revive Sticky grips were not remembering each time you went back in.  Maybe the same sort of bug for this setting.

**Comment by matzman666** [comment]
>  It is not remembering the setting each time I launch SteamVR.

When you change the audio input device in Advanced Settings and then open the SteamVR audio settings, is it also changed there?

**Comment by lghtanddrk** [comment]
Yes, while you are in the same session.  If I close out SteamVR and go back in then the settings change again.  It's saving the setting that OpenVR defaults to which is a different microphone on my computer. Every time I open OpenVR it keeps reverting back to the other microphone.

**Comment by matzman666** [comment]
Does the attached version work?

[OpenVR-AdvancedSettings.zip](https://github.com/matzman666/OpenVR-AdvancedSettings/files/784415/OpenVR-AdvancedSettings.zip)

**Comment by lghtanddrk** [comment]
There is no installer.  Where do I copy the files too?

**Comment by lghtanddrk** [comment]
Looks like that resolved the issue. Thanks!
