### ISSUE TITLE
Revive Settings Not Working Correctly

### ISSUE THREAD

**Issue by unkellsam** [matzman666/OpenVR-AdvancedSettings#28]
I have Revive 1.4 installed, however the Revive tab is grayed out by default. 

"Forcing" the Revive tab enables the tab, but the Revive grip settings do not actually change the grip behavior.  How can we properly install Revive in order to get Advanced Settings to properly interact with it?  It is installed in its default location in \program files.

**Comment by matzman666** [comment]
Do you see under SteamVR->Settings->Applications an entry for the Revive Overlay? Does the Revive application launcher appear in the dashboard?

When you change some settings in the Revive tab, then they get written into the steamvr.vrsettings file. When you change some settings on the Revive tab, do they get written into your steamvr.vrsettings file?

**Comment by unkellsam** [comment]
Yes, the Revive overlay is checked and the launcher appears in the dashboard.  I will get back to you on the changes to the settings file.

**Comment by unkellsam** [comment]
Seemingly solved.

The Revive tab started showing up without being forced after updating to your new release.

The grip settings weren't working in the game I tested because I had made a copy of the Revive injector in the game directory, which was from an older version of Revive, and I was injecting with that.  Injecting with the injector in the Revive installation directory solved the problem.
