### ISSUE TITLE
Supersampling slider doesn't work after SteamVR beta 2016-10-25 update

### ISSUE THREAD

**Issue by bgr** [matzman666/OpenVR-AdvancedSettings#3]
Based on the comment by aaron.leiby on the [update announcement page](https://steamcommunity.com/games/250820/announcements/detail/599369548909298226), there are now two supersampling-related parameters:

> The existing renderTargetMultiplier still applies the same as it always had for games.
> 
> However, it was also getting applied to the compositor's internal textures used render the dashboard, etc. which made it pretty easy to cause the compositor to drop frames if you set this too high, so I split the compositor's renderTargetMultiplier out separately so it can be set independently. The global setting still remains under the "steamvr" section, while the compositor specific value can be overridden in the "compositor" section.

This seems to cause the supersampling slider to have no effect.

**Comment by matzman666** [comment]
Fixed in version 2.0.
