### ISSUE TITLE
[Request] Ability to Rebind Input

### ISSUE THREAD

**Issue by skatardude10** [matzman666/OpenVR-AdvancedSettings#32]
Hey! 

It would be great to have a way to bind additional keys to controller buttons, or rebind the HMD button to do something else more useful.

For example, I have keybinds such as Ctrl + Right Arrow to change to the next song and Ctrl + P to pause music. If I could rebind the HMD system button to Ctrl + P to pause music or the left controller's menu button to Ctrl + Right Arrow, it would be SUPER super handy to not have to lift up the HMD and walk to my keyboard every 5 seconds I want to change songs :-P

What do you think ?

**Comment by StewieGriffin** [comment]
Click "Code" tab , then "releases"

**Comment by matzman666** [comment]
This is way out of scope for Advanced Settings. [FreePie](http://andersmalmgren.github.io/FreePIE/) is a much better candidate to implement something like this.
