### ISSUE TITLE
Bind grip button to back

### ISSUE THREAD

**Issue by bburky** [matzman666/OpenVR-AdvancedSettings#36]
In the Steam VR menus squeezing the grip button is the same as clicking the top left back button in the UI. Could you please add the same binding to OpenVR AdvancedSettings?

**Comment by matzman666** [comment]
This is unfortunately not possible. When the SteamVR dashboard is opened,  applications are supposed to enter a pause mode and ignore all controller button inputs. Valve enforces this by suppressing all button event when the dashboard is active. And without button events I cannot react to input.

**Comment by bburky** [comment]
Oh, that's too bad. Disappointing that they've limited the API like that.
