### ISSUE TITLE
Add "ToggleDelay" Option to Revive Menu

### ISSUE THREAD

**Issue by jaorg1234** [matzman666/OpenVR-AdvancedSettings#38]
Hey Matzman666!

Is it possible to add this option to the OpenVR Advanced Settings? I want to change this value depending on the game and right now going to the steamvr.vrsettings file to manually change it every time when loading up a game is kind of cumbersome.

**Comment by matzman666** [comment]
I hope I find a place on the Revive page for this, it's already pretty crowded. I will see what I can do.

**Comment by jaorg1234** [comment]
Thank you!

**Comment by matzman666** [comment]
Added in version 2.3.
