### ISSUE TITLE
Cannot edit/navigate options on OpenVr Dashboard.

### ISSUE THREAD

**Issue by isg530d** [matzman666/OpenVR-AdvancedSettings#39]
Hi,

I can view the openVr settings on the steamVR dashboard, but cannot navigate/change the settings.

If i use the desktop version then i can on the desktop.

Running with GTX 1080, SteamVR version 1486514237 Dated Feb 8th, 2017

regards

**Comment by matzman666** [comment]
What are you using to change the settings? A motion controller? gamepad? To other overlays like the Steam overlay work?

**Comment by isg530d** [comment]
Hi,

I'm using the xbox controller.

I do not have any other Steam overlays.

I can see the dashboard and navigate, but not into the OpenVR dashboard.

**Comment by dmalatesta** [comment]
I have the same issue, I can't seem to be able to navigate using mouse, keyboard, or xbox controller. All the rest of the menus work fine. Using an Oculus Rift.

**Comment by matzman666** [comment]
I currently [cannot support Gamepads](https://github.com/matzman666/OpenVR-AdvancedSettings/issues/13), and this application is a background application that has no window and thus cannot receive keyboard and mouse events.
