### ISSUE TITLE
UI messed up on high DPI system

### ISSUE THREAD

**Issue by LeoDavidson** [matzman666/OpenVR-AdvancedSettings#4]
When I open the OpenVR-AdvancedSettings UI, all the fonts are huge, too large for the spaces they are in and drawing on top of each other.

I suspect this is because my desktop is in high DPI mode (200% scaling, 24" 4k screen), and the font sizes are being increased due to that somehow. It doesn't affect the normal parts of the SteamVR dashboard (or anything else that I've noticed in the HMD).

Unfortunately, screenshots are broken in the current SteamVR beta so I am not sure if there is a good way to make a screenshot, if they can be made of the dashboard in the first place. If there is a way, and it would be useful, please let me know and I'll do it.

If there's anything you'd like me to try, confirm or check, please let me know. I'm a Windows desktop software developer so I don't know much about VR but I'm happy to do technical stuff if needed.

**Comment by matzman666** [comment]
Could you please create a file called "qt.conf" in the application directory with the content:
```
[Platforms]
WindowsArguments = dpiawareness=0
```
and try again. Please tell me whether it worked.

**Comment by LeoDavidson** [comment]
Yes, that fixes things! Many thanks!

**Comment by fire4cavemen** [comment]
I have the same problem on a 55" 4k TV Screen, 300% scaling. Tried to create the "qt.conf" file in the directory but it did not work. Am I doing something wrong? 

![untitled3](https://cloud.githubusercontent.com/assets/13317350/19836467/8d93b2a4-9ea1-11e6-9108-1ee5d3790677.png)

**Comment by matzman666** [comment]
Windows hides by default known file extensions. If you didn't have disabled this behaviour you probably have created a file called "qt.conf.txt".

Just download the file from [here](https://raw.githubusercontent.com/matzman666/OpenVR-AdvancedSettings/master/bin/win64/qt.conf) (right-click and save) and copy it into the application directory.

**Comment by matzman666** [comment]
Fix added with commit bb7ce53f49f030e119d61a08ac6433c42118359f.
