### ISSUE TITLE
SteamVRLauncher

### ISSUE THREAD

**Issue by tkapis** [matzman666/OpenVR-AdvancedSettings#46]
There is a java utility called SteamVRLauncher on GitHub which gives the possibility to set supersampling per game. It used to work perfectly but nowadays it crashes SteamVR when rebooting. I don't think it is supported anymore so is there a possibility that you could repair it or incorporate it in OpenVR Advanced Settings in some way?

https://www.reddit.com/r/Vive/comments/51jnky/steam_enhanced_vr_launcher_per_app_supersampling/

**Comment by matzman666** [comment]
Sorry, I currently have no time to repair that application or implement a game launcher.
