### ISSUE TITLE
Feature Request: Controller Offset in OpenVR Games

### ISSUE THREAD

**Issue by jaorg1234** [matzman666/OpenVR-AdvancedSettings#56]
Hello matzmann666,

just wanted to throw out a wishful feature request, not sure if it can be implemented: having the same offset controls like with the Revive tab, but only for OpenVR games as well. This would allow custom controllers, gun rigs and more to work better. Just from looking at the Rockband VR threads the offsetting via Revive works great and maybe the same could be done with OpenVR games.

If not, no biggie :)

**Comment by matzman666** [comment]
That's out-of-scope for Advanced Settings. But another [current project of mine](https://github.com/matzman666/OpenVR-InputEmulator) is about implementing controller offsets among other things.
