### ISSUE TITLE
Would it be possible to have the mic muted when the user takes the headset off?

### ISSUE THREAD

**Issue by xxTheGoDxx** [matzman666/OpenVR-AdvancedSettings#60]
I am not sure if you can read out the information from the headset sensor if the HMD is worn or not but some games seem to be able to do so (pausing the game for example when you take the headset off). If its possible, having the mic muted would be a great feature for privacy reasons but also to just reduce background chatter in MP games. 

I made a similar plea to Oculus in a reddit thread that was favorable received by users so there seems to be demand for such an option:

https://www.reddit.com/r/oculus/comments/6327jj/oculus_could_you_give_us_the_option_to_auto_mute/

Anyway, thanks for your work. Your tool really is a must.

**Comment by matzman666** [comment]
Yes, the headset proximity sensor state can be read via the OpenVR API, so it is possible to implement this. Will implement it in the next version.

**Comment by xxTheGoDxx** [comment]
Wow, thanks man.

**Comment by matzman666** [comment]
Added in [version 2.4](https://github.com/matzman666/OpenVR-AdvancedSettings/releases).
