### ISSUE TITLE
Crashes as soon as you try to change any settings

### ISSUE THREAD

**Issue by CorgiFat** [matzman666/OpenVR-AdvancedSettings#64]
Windows 7

Latest Steam Beta (SteamVR Home update)

1. Open up system menu
2. Open up Advanced Settings
3. Its working until I either select any options on the main screen or any option category such as audio or anything else, Advanced Settings stops responding. For example, I can drag the audio slider but as soon as I release it, it freezes and the responding window pops on the desktop side. Same for pressing any button or option. If I move the slider to 50%, then relaunch it manually from the folder, the 50% setting seems to save though I am not sure if it has any effect. 

Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	AdvancedSettings.exe
  Application Version:	0.0.0.0
  Application Timestamp:	58a60905
  Fault Module Name:	Qt5Quick.dll
  Fault Module Version:	5.7.0.0
  Fault Module Timestamp:	575c02b4
  Exception Code:	c0000005
  Exception Offset:	0000000000074ff2
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	7b59
  Additional Information 2:	7b59cfcc08644a3ee927dc71fa545976
  Additional Information 3:	0f64
  Additional Information 4:	0f6491a7dcd4c1868159773dfc691bfe

**Comment by matzman666** [comment]
Fixed in [version 2.4](https://github.com/matzman666/OpenVR-AdvancedSettings/releases).
