### ISSUE TITLE
OpenVR AdvancedSettings tab disappears

### ISSUE THREAD

**Issue by mamefan** [matzman666/OpenVR-AdvancedSettings#65]
It's been happening lately. I'm in SteamVR and click on the tab, and, once I click on SteamVR, the tab disappears entirely. If I turn off and back on SteamVR, it's there again, but the same thing will happen.

**Comment by MalekTaus** [comment]
I don't think OpenVR AdvancedSettings works with the latest steam vr update

**Comment by matzman666** [comment]
Fixed in [version 2.4](https://github.com/matzman666/OpenVR-AdvancedSettings/releases).
