### ISSUE TITLE
Fails to Restart via Restart button

### ISSUE THREAD

**Issue by S1llyG1t** [matzman666/OpenVR-AdvancedSettings#68]
Using the "Restart" button on the SteamVR page, fails to restart SteamVR.  The command window is throwing up an error about failing to find vrmonitor.exe, which I think may be related to Beta Update 1495066092.

"General:
Changed vrstartup to start vrmonitor regardless of the “start SteamVR from app launch” setting."

**Comment by matzman666** [comment]
Fixed in [version 2.4.1](https://github.com/matzman666/OpenVR-AdvancedSettings/releases).
