### ISSUE TITLE
[Enhancement] Replace center room square with a live HMD rotation circle?

### ISSUE THREAD

**Issue by kontemporary** [matzman666/OpenVR-AdvancedSettings#82]
So I can't remember the name of the setting but it puts a square on the ground to show the center of the physical room. So I thought it would be quite convenient to just have some type of arrow to show which way you have to rotate and the amount of spins. The counter could be the center room marker as well.

**Comment by matzman666** [comment]
Someone [has already implemented](https://github.com/benotter/TurnSignal) something like this in the meantime. Therefore I am closing this.
