### ISSUE TITLE
Chaperone profiles per game

### ISSUE THREAD

**Issue by olemartinorg** [matzman666/OpenVR-AdvancedSettings#84]
Hi!

Would it be possible to save different chaperone profiles by game? For instance, the blue chaperone is difficult to notice in SUPERHOT VR, so I usually set it to red or orange. For GORN, smashing into the TV happens easily, so forcing floor bounds (and/or increasing distance before drawing them) is a smart option to enable. It would be great if these settings (including chaperone color) could be auto-applied fro, OpenVR-AdvancedSettings whenever a certain game is started, and a default profile is reverted to after exiting those games.

Thougts on this? I think maybe it's what #51 is suggesting as well, although I don't believe it's communicated clearly there.

**Comment by matzman666** [comment]
You can already have profiles with different chaperone settings. Just click on "New Profile" on the top of the [Chaperone page](https://github.com/matzman666/OpenVR-AdvancedSettings#--chaperone-page). 

However, you have to manually apply them. Having them automatically applied when a game starts is theoretically possible, but requires quite some effort to implement and I currently don't have time to do this.

**Comment by dcbishop** [comment]
It would also be great to be able to implement super sampling settings pergame.

**Comment by xxTheGoDxx** [comment]
+1 for Super Sampling settings per game

Even w/o an automatic detection functionality being able to include the SS setting into a profile named after the game would be a significant advantage over having to remember the setting for each game.

**Comment by matzman666** [comment]
The newest version features supersampling profiles. They have to manually applied though. Any per-game settings are unlikely to be implemented any time soon.

**Comment by dcbishop** [comment]
Perhaps the next step would be a profile of profiles tied to something that can find the running SteamVR application.

**Comment by olemartinorg** [comment]
Yeah, I don't really agree this should be closed just yet. Even if supersampling profiles have been added, it doesn't do much for the rest of my suggestion. I fully understand that @matzman666 can't implement every feature request, but I wish this could stand in case someone else wants to tackle this.
