### ISSUE TITLE
State of checkboxes is confusing.

### ISSUE THREAD

**Issue by DiThi** [matzman666/OpenVR-AdvancedSettings#9]
Many people in /r/vive report that they set the opposite option than they wanted because the "dot" in the box when enabled makes it look like an empty box. The shape should be changed, for example to an X, a tick or a square of a different color than the background.

**Comment by matzman666** [comment]
Yeah, those checkboxes definitely need a redesign. It's on my to-do list.

**Comment by matzman666** [comment]
Uploaded a new version which fixes this problem, therefore I close this issue.
